name: test
on:
  workflow_call:
jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Set-up Node ğŸ“
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deps ğŸ“¦
        run: npm ci
      - name: Unit Tests ğŸ“
        run: npm run test
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4
      - name: Integration Tests ğŸ“
        uses: cypress-io/github-action@v6
        with:
          start: npm start
